---
- name: Set up Docker CE on Debian-family systems
  ansible.builtin.include_tasks: debian.yaml
  when: ansible_facts['os_family'] == "Debian"

- name: Set up Docker CE on RedHat-family systems
  ansible.builtin.include_tasks: redhat.yaml
  when: ansible_facts['os_family'] == "RedHat"

- name: Start and enable Docker service
  ansible.builtin.service:
    name: "{{ docker_ce_service_name }}"
    enabled: "{{ docker_ce_service_enabled }}"
    state: "{{ docker_ce_service_state }}"

- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_ce_users }}"
