# {{ ansible_managed }}
[commands]
upgrade_type = {{ 'security' if unattended_upgrades_security_only else 'default' }}
random_sleep = 0
network_online_timeout = 60
download_updates = yes
apply_updates = {{ 'yes' if unattended_upgrades_dnf_apply_updates else 'no' }}
reboot = {{ 'when-needed' if unattended_upgrades_auto_reboot else 'never' }}

[emitters]
system_name =
emit_via = stdio

[email]
{% if unattended_upgrades_mail %}
email_from = root
email_to = {{ unattended_upgrades_mail }}
email_host = localhost
{% endif %}

[base]
debuglevel = 1
