---
unattended_upgrades_security_only: true
unattended_upgrades_auto_reboot: false
unattended_upgrades_auto_reboot_time: "02:00"
unattended_upgrades_remove_unused_dependencies: true
unattended_upgrades_mail: ""
unattended_upgrades_mail_only_on_error: true
unattended_upgrades_apt_update_interval_days: 1
unattended_upgrades_apt_upgrade_interval_days: 1
unattended_upgrades_apt_autoclean_interval_days: 7
unattended_upgrades_dnf_apply_updates: true
