# {{ ansible_managed }}
Port {{ ssh_port }}
PermitRootLogin {{ ssh_permit_root_login }}
PasswordAuthentication {{ 'yes' if ssh_password_authentication else 'no' }}
PubkeyAuthentication {{ 'yes' if ssh_pubkey_authentication else 'no' }}
PermitEmptyPasswords {{ 'yes' if ssh_permit_empty_passwords else 'no' }}
KbdInteractiveAuthentication {{ 'yes' if ssh_kbd_interactive_authentication else 'no' }}
KerberosAuthentication {{ 'yes' if ssh_kerberos_authentication else 'no' }}
GSSAPIAuthentication {{ 'yes' if ssh_gssapi_authentication else 'no' }}
X11Forwarding {{ 'yes' if ssh_x11_forwarding else 'no' }}
AllowTcpForwarding {{ 'yes' if ssh_allow_tcp_forwarding else 'no' }}
AllowAgentForwarding {{ 'yes' if ssh_allow_agent_forwarding else 'no' }}
MaxAuthTries {{ ssh_max_auth_tries }}
LoginGraceTime {{ ssh_login_grace_time }}
ClientAliveInterval {{ ssh_client_alive_interval }}
ClientAliveCountMax {{ ssh_client_alive_count_max }}
{% if ssh_allow_users %}
AllowUsers {{ ssh_allow_users | join(' ') }}
{% endif %}
{% if ssh_allow_groups %}
AllowGroups {{ ssh_allow_groups | join(' ') }}
{% endif %}
{% if ssh_deny_users %}
DenyUsers {{ ssh_deny_users | join(' ') }}
{% endif %}
{% if ssh_deny_groups %}
DenyGroups {{ ssh_deny_groups | join(' ') }}
{% endif %}
