---
name: Lint

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: pip install -r requirements-dev.txt

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r requirements.yaml

      - name: Run yamllint
        run: yamllint .

      - name: Run ansible-lint
        run: ansible-lint
